/** Declared capabilities a Channel Provider may support. iCal supports a subset. */
const CAPABILITIES = {
  AVAILABILITY_PULL: 'availability_pull',
  AVAILABILITY_PUSH: 'availability_push',
  RATES_PULL: 'rates_pull',
  RATES_PUSH: 'rates_push',
  RESTRICTIONS_PUSH: 'restrictions_push',
  RESERVATIONS_PULL: 'reservations_pull',
  RESERVATIONS_WEBHOOK: 'reservations_webhook',
  CANCELLATIONS_PULL: 'cancellations_pull',
  MODIFICATIONS_PULL: 'modifications_pull',
  UNIT_MAPPING: 'unit_mapping',
  RATE_PLAN_MAPPING: 'rate_plan_mapping',
  MESSAGES_PULL: 'messages_pull',
  MESSAGES_SEND: 'messages_send',
};

const ICAL_CAPABILITIES = [
  CAPABILITIES.AVAILABILITY_PULL,
  CAPABILITIES.AVAILABILITY_PUSH,
  CAPABILITIES.UNIT_MAPPING,
];

const FULL_API_CAPABILITIES = [
  CAPABILITIES.AVAILABILITY_PULL,
  CAPABILITIES.AVAILABILITY_PUSH,
  CAPABILITIES.RATES_PULL,
  CAPABILITIES.RATES_PUSH,
  CAPABILITIES.RESTRICTIONS_PUSH,
  CAPABILITIES.RESERVATIONS_PULL,
  CAPABILITIES.RESERVATIONS_WEBHOOK,
  CAPABILITIES.CANCELLATIONS_PULL,
  CAPABILITIES.MODIFICATIONS_PULL,
  CAPABILITIES.UNIT_MAPPING,
  CAPABILITIES.RATE_PLAN_MAPPING,
  CAPABILITIES.MESSAGES_PULL,
  CAPABILITIES.MESSAGES_SEND,
];

module.exports = {
  CAPABILITIES,
  ICAL_CAPABILITIES,
  FULL_API_CAPABILITIES,
};
