
export const FACILITY_SUGGESTIONS = [
  '24/7 security & CCTV',
  '24/7 security',
  'Gated entry',
  'Doorman / bawab',
  'Concierge / customer care',
  'Housekeeping services',
  'Maintenance services',
  'Backup generator',
  'Elevators',
  'Guest parking',
  'Underground parking',
  'Swimming pools',
  'Outdoor pools',
  'Kids pool',
  'Clubhouse',
  'Community hub',
  'Gym / Health club',
  'Fully equipped gym',
  'Outdoor gym',
  'Spa & wellness',
  'Health club (gym, spa, sauna, jacuzzi)',
  'Sports courts (tennis / padel)',
  'Sports facilities & courts',
  'Golf course',
  'Jogging & cycling tracks',
  'Walking, jogging & cycling tracks',
  'Landscaped gardens',
  'Central park',
  'Green spaces & botanical gardens',
  'Kids play area',
  'Kids entertainment area',
  'Commercial strip / retail',
  'Commercial hub (shops / F&B)',
  'Commercial mall / retail',
  'Restaurants & cafes',
  'Nile-side cafes & restaurants',
  'Nile corniche walk',
  'Hypermarket / grocery',
  'Pharmacy / medical clinic',
  'Medical center & pharmacy',
  'International schools nearby',
  'Business hub',
  'Co-working space',
  'Cultural center',
  'Art galleries nearby',
  'Metro station nearby',
  'Mosque',
  'Barbecue area',
  'Yoga / meditation areas',
  'Nightlife / lounges',
  'Hotel / hospitality',
];
